### PR TITLE
fix: Response.json() should not check the content-type

### LINKED ISSUE #228: Allow all application/*+json media types to be parsed with response.json()
### 🚀 Feature Proposal

Currently, light-my-request explicitly requires the response's content type to start with exactly "application/json". 

https://github.com/fastify/light-my-request/blob/f895e9a3045da411a30cfe82435b4c284054bb9a/lib/response.js#L142

However, there are several adjacent subtypes, which imply JSON.parse will work, theoretically all:

```
application/[tree "."] subtype +json* [";" parameter]
```

### Motivation

I set the response's content type to "application/geo+json", my `response.json()` calls started throwing errors.

### Example

- https://www.iana.org/assignments/media-types/application/vnd.geo+json
- https://www.iana.org/assignments/media-types/application/geo+json

According to IANA, this applies to roughly 100 more media types: [Source](https://www.iana.org/assignments/media-types/media-types.xhtml)

### PR DESCRIPTION
**Pull request by WoH**
Closes #228 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

File: lib/response.js [hunk 1]
```diff
@@ -139,8 +139,8 @@ function generatePayload (response) {
 
   // Prepare payload parsers
   res.json = function parseJsonPayload () {
-    if (res.headers['content-type'].indexOf('application/json') < 0) {
-      throw new Error('The content-type of the response is not application/json')
+    if (!/^application\/(?<tree>([\w-]*\.)*)(?<subtype>[\w-]*\+)?json(.*)$/.test(res.headers['content-type'])) {
```
Comment (climba03003) [inline lib/response.js:142]: I am thinking, would it be better to remove the check entirely.

The function here is more or less the same as `fetch`. And it should not block the parsing based on `Content-Type`.

Comment (WoH) [reply lib/response.js:142]: I am happy to remove it entirely in case that's a better way to approach it. But I assume this is not supposed to get too close to fetch (i.e. adding the content type if it wasn't set)?

Comment (climba03003) [reply lib/response.js:142]: I means `.json` is just doing `JSON.parse` which is a helper function only (same as `fetch`).

Comment (climba03003) [reply lib/response.js:142]: Let see what the others think about it. 
@fastify/core 

I am also fine for the current implementation. @WoH And it is missing document update.
https://github.com/fastify/light-my-request/blob/f895e9a3045da411a30cfe82435b4c284054bb9a/README.md?plain=1#L184

Comment (WoH) [reply lib/response.js:142]: Thanks for the hint, let me know if my attempts at an explanation that doesn't sound too confusing worked 😅

Comment (Uzlopak) [reply lib/response.js:142]: Looks kind of a potential performance bottleneck. Also why are there named groups if you just use .test() and no .match()? 

Also safe-regex shows that the regex is potentially unsafe.

Comment (WoH) [reply lib/response.js:142]: Groups to have a better idea what is going on. The current benchmarks ignore this, so posting them didn't seem helpful, I assume 'application/json' is the most common content type by far, maybe check that first and skip the regex?

Comment (mcollina) [reply lib/response.js:142]: I would just drop the check to be honest.

Comment (kibertoad) [reply lib/response.js:142]: +1 to dropping the check

**Review by climba03003 — APPROVED** [review]

File: lib/response.js (hunk 1 above)
Comment (WoH) [reply lib/response.js]: Dropped the check, let me know it if I should change anything else.

**Review by RafaelGSS — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by kibertoad — APPROVED** [review]
