### PR TITLE
fix: add missing request.socket (#87)

### LINKED ISSUE #87: Missing socket
Hi,
I'm writing some test for a Fastify plugin that uses some `koa` handler to manage routes.

The test is failing due this check of `koa` lib:

```
if (this.socket.encrypted) return 'https';
```
https://github.com/koajs/koa/blob/master/lib/request.js#L402

Considered that:
- the final solution would be to implement a native plugin for Fastify
- light my request says "**Does not use a socket connection**.."
- I can use `listen` instead of `inject` to write my tests

Do you think adding a `this.socket = {}` to the light-my-request is a bad idea?
How would you cover this use case?

### PR DESCRIPTION
**Pull request by humphd**
Fixes #87.  This adds the `.socket` property to `request`, mirroring the `.connection` property

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — COMMENTED** [review]
Could you add a test case?

File: lib/request.js [hunk 1]
```diff
@@ -67,6 +67,7 @@ function Request (options) {
   this.connection = {
     remoteAddress: options.remoteAddress || '127.0.0.1'
   }
+  this.socket = this.connection
```
Comment (jsumners) [inline lib/request.js:70]: Should there be some sort of deprecation here? We'd have to follow the upstream deprecation cycle.

Comment (climba03003) [reply lib/request.js:70]: I think you can add the deprecate warning in the [typing](https://github.com/fastify/light-my-request/blob/master/index.d.ts#L63) to something like this
```typescript
interface Request extends stream.Readable {
...
// @deprecated
connection: object
...
```

Comment (delvedor) [reply lib/request.js:70]: I agree with @jsumners.
According to the [Node.js docs](https://nodejs.org/api/http.html#http_request_connection), `.connection` has been deprecated in favor of `.socket`.
I think we should do something like this:
```js
this.socket = {
  remoteAddress: options.remoteAddress || '127.0.0.1'
}

Object.defineProperty(Request, 'connection', {
  get () {
    // if node major ≥13 emit a warning with https://github.com/fastify/fastify-warning
    return this.socket
  }
})
```

Comment (mcollina) [reply lib/request.js:70]: +1!

**Comment by humphd** [comment]
Thanks for all the feedback.  I've tried to make the changes/updates that were requested.  Let me know if I've done it incorrectly, or there are other things I should consider.

File: lib/request.js [hunk 2]
```diff
@@ -64,10 +64,17 @@ function Request (options) {
...
 
-  this.connection = {
+  this.socket = {
     remoteAddress: options.remoteAddress || '127.0.0.1'
   }
-  this.socket = this.connection
+
+  Object.defineProperty(this, 'connection', {
+    get () {
+      // if node major ≥13 emit a warning with https://github.com/fastify/fastify-warning
```
Comment (jsumners) [inline lib/request.js:73]: The comment here is not sufficient. An actual test against against `process.version` is needed along with a warning issued through the interface that `fastify-warning` provides.

Comment (humphd) [reply lib/request.js:73]: Understood.  Maybe something like https://github.com/fastify/fastify-plugin/blob/d3b2ca47404e622f7c474493bb0624bf95a2e4f4/test/esm/index.test.js#L6, and then use fastify-warning to actually log that message?

Comment (jsumners) [reply lib/request.js:73]: Correct. Fastify itself uses `fastify-warning` to issue deprecation notices. You can learn from there as well.

Comment (humphd) [reply lib/request.js:73]: Great, thanks @jsumners, this is really helpful.  I'll dig around and update this to do it correctly.

**Comment by mcollina** [comment]
Any update on this @humphd ?

**Comment by humphd** [comment]
I've submitted another fix, which uses `semver` to do the check against the node version, and `fastify-warning` to emit the deprecation warning.  Thanks to @jsumners for pointing out how I should do this.

A couple things I wasn't sure about related to the way I named things in `warning.create()`, specifically the `CODE` and if there is a standard you want to use.  Also, I noticed that in some places you create all the warnings in a single file.  I did it in the `request.js` file, but could move it.

Also, I ran into a small issue with naming on the code, where I had lowercase letters for the plugin name, but everything gets converted to uppercase.  I'll send a PR to the docs for `fastify-warning` to make that more clear.

File: lib/request.js [hunk 3]
```diff
@@ -64,10 +69,20 @@ function Request (options) {
...
   }
 
-  this.connection = {
+  this.socket = {
     remoteAddress: options.remoteAddress || '127.0.0.1'
   }
 
+  Object.defineProperty(this, 'connection', {
+    get () {
+      if (semver.gte(process.versions.node, '13.0.0')) {
```
[the remark this answers is not in the document]
Comment (jsumners) [reply lib/request.js:78]: Sounds good to me.

**Comment by humphd** [comment]
Updated to remove `semver` and do the warning on `.connection` regardless of version.

**Review by jsumners — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm
